/**
 * gen-shl.ts (bun) — package the longitudinal example Bundle as a SMART Health
 * Link: encrypt it (compact JWE, dir/A256GCM) and emit the committed artifacts
 * the viewer and docs consume. Direct-file mode (flag "U").
 *
 *   input/images/viewer/example.jwe   the ciphertext (published static asset)
 *   input/images/viewer/shlink.txt    canonical shlink:/ for the published site
 *   input/images/viewer/_shlink-local.txt     bare shlink:/ for localhost testing
 *   input/images/viewer/_shlink-local-ig.txt  shlink:/ for localhost:5525 testing
 *                                            (underscore -> not published)
 *
 * Run ahead of the publisher:  bun scripts/gen-shl.ts
 */
import { mkdir } from "node:fs/promises";
import { encryptCompact, b64uFromBytes, bytesFromB64u } from "../viewer-src/jwe.mjs";

// The canonical viewer is our standalone GitHub Pages deployment at
// periodicity.fhir.me (the IG-published copy at build.fhir.org can't be relied
// on — its output strips/blocks unchecked active JS). A full shareable link is
// <viewer>/#shlink:/<payload>; the payload's `url` is the ciphertext location.
//
// example.jwe is published in BOTH places (it's committed under
// input/images/viewer/, which the Pages deploy and the IG Publisher each copy),
// so we emit two demo links for two purposes:
//   - shlink.txt (co-located on Pages): embeds the same-origin Pages jwe — this
//     is what the viewer's "Load the synthetic demo" button uses.
//   - the spec's demo includes: embed the SPEC-hosted jwe under FILE_BASE and
//     prefix the external viewer, demonstrating the full cross-origin handoff
//     (spec hosts its own copy of the data, passes out to the external viewer).
// Both jwe copies are byte-identical (same committed file, same fixed key), so
// either link decrypts. Override VIEWER_BASE / FILE_BASE for a fork or rehost.
const DEFAULT_VIEWER_BASE = "https://periodicity.fhir.me";
const DEFAULT_FILE_BASE = "https://build.fhir.org/ig/jmandel/periodicity/viewer";
const VIEWER_BASE = normalizeBase(Bun.env.VIEWER_BASE || DEFAULT_VIEWER_BASE);
const FILE_BASE = normalizeBase(Bun.env.FILE_BASE || DEFAULT_FILE_BASE);
const LABEL = "Periodicity — synthetic longitudinal period-tracking export";
const dir = `${import.meta.dir}/../input/images/viewer`;
const includesDir = `${import.meta.dir}/../input/includes`;
const root = `${import.meta.dir}/..`;

// FIXED public demo key + IV: this is synthetic data meant to be openable by
// anyone, and pinning them makes example.jwe / shlink.txt byte-stable
// across builds (no churn) so the link can be documented on the examples page.
// NEVER reuse a fixed key/IV for real patient data — gen a fresh random key+IV.
const keyB64 = "-iXXJ2n57QEfYcKZPqjzvde4Y_XaBdqjzmRUvRhwVcI";
const ivB64 = "wrcwWOZXCZuO6fMQ";
const key = bytesFromB64u(keyB64);

const bundle = await Bun.file(`${root}/input/resources/Bundle-period-tracking-longitudinal-example.json`).text();

const jwe = await encryptCompact(bundle, key, { iv: bytesFromB64u(ivB64) });
await Bun.write(`${dir}/example.jwe`, jwe);

const enc = new TextEncoder();
const shlinkPayload = (fileUrl: string) => "shlink:/" + b64uFromBytes(enc.encode(JSON.stringify({ url: fileUrl, key: keyB64, flag: "U", label: LABEL, v: 1 })));
const share = (viewer: string, file: string) => `${viewer}#${shlinkPayload(file)}`;
const htmlEscape = (value: string) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function normalizeBase(value: string) {
  const trimmed = value.trim();
  if (!trimmed) throw new Error("VIEWER_BASE must not be empty");
  return trimmed.replace(/\/+$/, "");
}

await mkdir(includesDir, { recursive: true });

// co-located sample link (Pages viewer + same-origin Pages jwe) — backs the
// viewer's "Load the synthetic demo" button and is a self-contained share link.
const sampleUrl = share(`${VIEWER_BASE}/`, `${VIEWER_BASE}/example.jwe`);
await Bun.write(`${dir}/shlink.txt`, sampleUrl + "\n");
// spec demo link (external viewer + spec-hosted jwe) — the full cross-origin
// handoff documented on the IG pages.
const shareUrl = share(`${VIEWER_BASE}/`, `${FILE_BASE}/example.jwe`);
// local test links (underscore -> not published by the IG Publisher)
const localFileUrl = "http://localhost:5525/viewer/example.jwe";
await Bun.write(`${dir}/_shlink-local.txt`, shlinkPayload(localFileUrl) + "\n");
await Bun.write(`${dir}/_shlink-local-ig.txt`, share("http://localhost:5525/viewer/", localFileUrl) + "\n");

await Bun.write(`${includesDir}/demo-shlink-link.xhtml`, [
  "<!-- generated by scripts/gen-shl.ts; do not edit by hand -->",
  `<a href="${htmlEscape(shareUrl)}" target="_blank" rel="noopener">clinician viewer demo</a>`,
  "",
].join("\n"));

await Bun.write(`${includesDir}/demo-shlink-block.md`, [
  "<!-- generated by scripts/gen-shl.ts; do not edit by hand -->",
  `[**▶ Open the longitudinal example in the clinician viewer**](${shareUrl}){:target="_blank" rel="noopener"}`,
  "",
  "The shareable SMART Health Link (viewer-prefixed `shlink:/…`) — copy it, or open it on any device:",
  "",
  "```",
  shareUrl,
  "```",
  "",
].join("\n"));

console.log(`wrote example.jwe (${jwe.length} chars), shlink.txt (+ local test links)`);
console.log(`  wrote input/includes/demo-shlink-{link.xhtml,block.md}`);
console.log(`  key=${keyB64.slice(0, 10)}… (fixed public demo key)`);
console.log(`  viewer=${VIEWER_BASE}  (sample jwe co-located; spec demo jwe=${FILE_BASE}/example.jwe)`);
