/**
 * gen-shl.ts (bun) — package the longitudinal example Bundle as a SMART Health
 * Link: encrypt it (compact JWE, dir/A256GCM) and emit the committed artifacts
 * the viewer and docs consume. Direct-file mode (flag "U").
 *
 *   input/images/viewer/example.jwe   the ciphertext (published static asset)
 *   input/images/viewer/shlink.txt    canonical shlink:/ for the published site
 *   input/images/viewer/_shlink-local.txt     bare shlink:/ for localhost testing
 *   input/images/viewer/_shlink-local-ig.txt  shlink:/ for localhost:5525 testing
 *                                            (underscore -> not published)
 *
 * Run ahead of the publisher:  bun scripts/gen-shl.ts
 */
import { mkdir } from "node:fs/promises";
import { encryptCompact, b64uFromBytes, bytesFromB64u } from "../viewer-src/jwe.mjs";

// Both the viewer and the demo ciphertext are served from our standalone
// GitHub Pages deployment at periodicity.fhir.me. Two reasons it must host the
// jwe, not the spec:
//   1. The IG-published viewer (build.fhir.org / eventually hl7.org) can't be
//      relied on — its output strips/blocks unchecked active JS.
//   2. The demo link is published *in the spec*, but a browser viewer fetches
//      the jwe cross-origin, which needs CORS. build.fhir.org sends CORS today,
//      but hl7.org (the canonical home) does NOT — so a spec-hosted jwe URL
//      would break the demo the moment we publish there. periodicity.fhir.me
//      (a CORS-enabled host we control) keeps the link working everywhere.
// So the spec mints links whose `.url` points at periodicity.fhir.me, even
// though the link itself lives on the spec page. A full shareable link is
// <viewer>/#shlink:/<payload>. Override VIEWER_BASE for a fork or rehost.
const DEFAULT_VIEWER_BASE = "https://periodicity.fhir.me";
const VIEWER_BASE = normalizeBase(Bun.env.VIEWER_BASE || DEFAULT_VIEWER_BASE);
const LABEL = "Periodicity — synthetic longitudinal period-tracking export";
const dir = `${import.meta.dir}/../input/images/viewer`;
const includesDir = `${import.meta.dir}/../input/includes`;
const root = `${import.meta.dir}/..`;

// FIXED public demo key + IV: this is synthetic data meant to be openable by
// anyone, and pinning them makes example.jwe / shlink.txt byte-stable
// across builds (no churn) so the link can be documented on the examples page.
// NEVER reuse a fixed key/IV for real patient data — gen a fresh random key+IV.
const keyB64 = "-iXXJ2n57QEfYcKZPqjzvde4Y_XaBdqjzmRUvRhwVcI";
const ivB64 = "wrcwWOZXCZuO6fMQ";
const key = bytesFromB64u(keyB64);

const bundle = await Bun.file(`${root}/input/resources/Bundle-period-tracking-longitudinal-example.json`).text();

const jwe = await encryptCompact(bundle, key, { iv: bytesFromB64u(ivB64) });
await Bun.write(`${dir}/example.jwe`, jwe);

const enc = new TextEncoder();
const shlinkPayload = (fileUrl: string) => "shlink:/" + b64uFromBytes(enc.encode(JSON.stringify({ url: fileUrl, key: keyB64, flag: "U", label: LABEL, v: 1 })));
const share = (viewer: string, file: string) => `${viewer}#${shlinkPayload(file)}`;
const htmlEscape = (value: string) => value.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function normalizeBase(value: string) {
  const trimmed = value.trim();
  if (!trimmed) throw new Error("VIEWER_BASE must not be empty");
  return trimmed.replace(/\/+$/, "");
}

await mkdir(includesDir, { recursive: true });

// The shareable link: external viewer + the CORS-durable Pages jwe. Used both
// for shlink.txt (co-located on Pages; also backs the viewer's "Load the
// synthetic demo" button) and for the demo links published in the spec.
const shareUrl = share(`${VIEWER_BASE}/`, `${VIEWER_BASE}/example.jwe`);
await Bun.write(`${dir}/shlink.txt`, shareUrl + "\n");
// local test links (underscore -> not published by the IG Publisher)
const localFileUrl = "http://localhost:5525/viewer/example.jwe";
await Bun.write(`${dir}/_shlink-local.txt`, shlinkPayload(localFileUrl) + "\n");
await Bun.write(`${dir}/_shlink-local-ig.txt`, share("http://localhost:5525/viewer/", localFileUrl) + "\n");

await Bun.write(`${includesDir}/demo-shlink-link.xhtml`, [
  "<!-- generated by scripts/gen-shl.ts; do not edit by hand -->",
  `<a href="${htmlEscape(shareUrl)}" target="_blank" rel="noopener">clinician viewer demo</a>`,
  "",
].join("\n"));

await Bun.write(`${includesDir}/demo-shlink-block.md`, [
  "<!-- generated by scripts/gen-shl.ts; do not edit by hand -->",
  `[**▶ Open the longitudinal example in the clinician viewer**](${shareUrl}){:target="_blank" rel="noopener"}`,
  "",
  "The shareable SMART Health Link (viewer-prefixed `shlink:/…`) — copy it, or open it on any device:",
  "",
  "```",
  shareUrl,
  "```",
  "",
].join("\n"));

console.log(`wrote example.jwe (${jwe.length} chars), shlink.txt (+ local test links)`);
console.log(`  wrote input/includes/demo-shlink-{link.xhtml,block.md}`);
console.log(`  key=${keyB64.slice(0, 10)}… (fixed public demo key)`);
console.log(`  viewer=${VIEWER_BASE}  (jwe at ${VIEWER_BASE}/example.jwe — CORS-durable for spec + Pages)`);
